PREFIX = x86_64-w64-mingw32
SDL2_PATH = $(HOME)/SDL2
ifeq ($(OS),Windows_NT)
SUFFIX = .exe
LFLAGS := -L$(SDL2_PATH)/libs -lSDL2 -lSDL2main
INCLUDE = -I$(SDL2_PATH)/include/SDL2
else
CFLAGS = `sdl2-config --cflags`
SUFFIX =
endif

LFLAGS += -lm -mwindows -lmingw32

OUT := $(NAME).exe

CC := $(PREFIX)-gcc$(SUFFIX)
AR := $(PREFIX)-gcc-ar$(SUFFIX)
