CFLAGS := -Wall -s USE_SDL=2 --embed-file main.lua --embed-file goblin.png --shell-file index.html
LFLAGS := -lpthread -lm -ldl -lSDL2
OUT := $(NAME).html
CLEAR_FILES := cafe.js cafe.wasm

CC := emcc
AR := emar
